print("Welcome to the Basketball Roster Program")
roster = []
print()
a = input("Who is your point guard: ").title()
roster.append(a)
b = input("Who is your shooting guard: ").title()
roster.append(b)
c = input("Who is your samll forward : ").title()
roster.append(c)
d = input("Who is your power forward: ").title()
roster.append(d)
e = input("Who is your center: ").title()
roster.append(e)
print()
print("\tYour starting 5 for the upcoming basketball season\n\tpoint guard:\t{}\n\tshooting guard:\t{}\n\tSmall forward:\t{}\n\tpower forward:\t{}\n\tCenter:\t{}".format(a,b,c,d,e))
injured_player = roster.remove(c)
print()
print("Oh no, {} is injured".format(c))
print("Your roster has only {} players".format(len(roster)))
print("who will be the {} spot: ".format(c), end = '')
added_player = input().title()
roster.insert(2,added_player)
print("\tYour starting 5 for the upcoming basketball season\n\tpoint guard:\t{}\n\tshooting guard:\t{}\n\tSmall forward:\t{}\n\tpower forward:\t{}\n\tCenter:\t{}".format(a,b,added_player,d,e))
print()
print("Good luck {} you will do great!\nYour roster now has {} players".format(added_player,len(roster)))