print("Welcome to the letter counter app ")
a = input("What is your name: ")
print("Hello "+ a + "!")
print("I will count the number of times that a specific letter occurs in a message")
b = input("Please enter the message: ")
e = b.lower()
c = input("which letter would you like to count the occurrence of : ")
c = c.lower()
d = e.count(c)
print("{}, your message has {} {}'s in it".format(a,d,c))