print("Welcome to the Grade Sorter App")
print()
a = int(input("what is your first grade(0-100): "))
b = int(input("what is your second grade(0-100): "))
c = int(input("what is your third grade(0-100): "))
d = int(input("what is your fourth grade(0-100): "))
ls = []
ls.append(a)
ls.append(b)
ls.append(c)
ls.append(d)
print("Your grades are:{}".format(ls))
ls.sort(reverse=True)
print("Your grades from highest to lowest are: {}".format(ls))
print("Lowest two grades will now be dropped")
print("Removed grade: {}".format(ls.pop()))
print("Removed grade: {}".format(ls.pop()))
print("Your remaining grades are: {}".format(ls))
print("Nice work! Your highest grades are {}".format(max(ls)))