import datetime
print("Welcome to the Grocery List App")
ls = ["meat","cheese"]
time = datetime.datetime.now()
month = str(time.month)
day = str(time.day)
hour = str(time.hour)
minute = str(time.minute)
print("Current date and time {}/{} {}:{}".format(month, day, hour, minute))
f = input("Type of food to add to the grocery list: ")
ls.append(f)
f = input("Type of food to add to the grocery list: ")
ls.append(f)
f = input("Type of food to add to the grocery list: ")
ls.append(f)
print()
print("Here is your grocery list: \n{}".format(ls))
ls = sorted(ls)
print("Here is your grocery list soted: {}".format(ls))
print()
print("Simulating grocery shop")
print()
print("Current grocery list : {} items\n{}".format(len(ls), ls))
a = input("What food did you just buy: ")
print("Remove {} from list".format(a))
ls.remove(a)
print("Current grocery list : {} items\n{}".format(len(ls), ls))
a = input("What food did you just buy: ")
print("Remove {} from list".format(a))
ls.remove(a)
print("Current grocery list : {} items\n{}".format(len(ls), ls))
a = input("What food did you just buy: ")
print("Remove {} from list".format(a))
ls.remove(a)
print("Current grocery list : {} items\n{}".format(len(ls), ls))
b = ls.pop()
print("Sorry, the store is out of {}".format(b))
a = input("What food would you like instead: ")
ls.append(a)
print("Here is what remains in your grocery list\n{}".format(ls))

